//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SpikeHorizontalNavigation.Module.BusinessObjects.SpikeHorizontalNavigation
{

    public partial class Asset : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fSerialNo;
        public string SerialNo
        {
            get { return fSerialNo; }
            set { SetPropertyValue<string>(nameof(SerialNo), ref fSerialNo, value); }
        }
        Owner fOwner;
        [Association(@"AssetReferencesOwner")]
        public Owner Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Owner>(nameof(Owner), ref fOwner, value); }
        }
    }

}
