//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SpikeHorizontalNavigation.Module.BusinessObjects.SpikeHorizontalNavigation
{

    public partial class Owner : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fID;
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        [Association(@"AssetReferencesOwner")]
        public XPCollection<Asset> Assets { get { return GetCollection<Asset>(nameof(Assets)); } }
    }

}
